# Generated by Django 3.1.12 on 2021-06-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500, unique=True)),
                ('Inheritance', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chromosome', models.CharField(max_length=2)),
                ('Start', models.IntegerField()),
                ('End', models.IntegerField()),
                ('Symbol', models.CharField(max_length=50)),
                ('Disease', models.ManyToManyField(to='GenDVApp.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chromosome', models.CharField(max_length=2)),
                ('Position', models.IntegerField()),
                ('Code', models.CharField(max_length=50, unique=True)),
                ('Reference', models.CharField(blank=True, max_length=50, null=True)),
                ('Alternative', models.CharField(blank=True, max_length=50, null=True)),
                ('Gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GenDVApp.gene')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='Variant',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GenDVApp.variant'),
        ),
        migrations.AddField(
            model_name='disease',
            name='Gene',
            field=models.ManyToManyField(to='GenDVApp.Gene'),
        ),
    ]
