# Generated by Django 3.1.12 on 2021-06-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenDVApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='Gene',
            field=models.ManyToManyField(null=True, to='GenDVApp.Gene'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='Disease',
            field=models.ManyToManyField(null=True, to='GenDVApp.Disease'),
        ),
    ]
