# Generated by Django 3.1.12 on 2021-06-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GenDVApp', '0002_auto_20210627_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='Gene',
            field=models.ManyToManyField(blank=True, null=True, to='GenDVApp.Gene'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='Disease',
            field=models.ManyToManyField(blank=True, null=True, to='GenDVApp.Disease'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GenDVApp.gene'),
        ),
    ]
