# Generated by Django 3.1.12 on 2021-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenDVApp', '0003_auto_20210627_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='Variant',
        ),
        migrations.AddField(
            model_name='gene',
            name='Variant',
            field=models.ManyToManyField(blank=True, null=True, to='GenDVApp.Variant'),
        ),
    ]
